#!/bin/sh
# Commented this line since it seems to produce an infinite loop in husky@9.1.1
# . "$(dirname "$0")/h"

prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
