name: build-and-publish
on:
  push:
    branches:
      - '**'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js & npm
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Prettification Check
        run: npm run prettification-check
      - name: Linting
        run: npm run lint
      - name: Run Build Script
        run: npm run build
      - name: Publish if version has been updated
        if: ${{ github.ref_name == 'main' }}
        uses: JS-DevTools/npm-publish@v4
